Revert "New tweepy for 'No active exception to reraise' fix"
This reverts commit b2eca49c939d818677e7023c3c0f9b17d3e69ac8.

    Traceback (most recent call last):
      File ".../fewerror/twitter.py", line 66, in <module>
        main()
      File ".../fewerror/twitter.py", line 62, in main
        stream.userstream()
      File ".../env/lib/python3.4/site-packages/tweepy/streaming.py", line 379, in userstream
        self._start(async)
      File ".../env/lib/python3.4/site-packages/tweepy/streaming.py", line 346, in _start
        self._run()
      File ".../env/lib/python3.4/site-packages/tweepy/streaming.py", line 286, in _run
        raise exception
      File ".../env/lib/python3.4/site-packages/tweepy/streaming.py", line 255, in _run
        self._read_loop(resp)
      File ".../env/lib/python3.4/site-packages/tweepy/streaming.py", line 298, in _read_loop
        line = buf.read_line().strip()
      File ".../env/lib/python3.4/site-packages/tweepy/streaming.py", line 171, in read_line
        self._buffer += self._stream.read(self._chunk_size)
    TypeError: Can't convert 'bytes' object to str implicitly